<a href="https://colab.research.google.com/github/santisalam/clase_econometria/blob/main/Copia_de_econometria_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INTEGRANTES JUAN PABLO, VANESSA GIL , SANTIAGO, SERGIO ANDRES 

Instale la librería wooldridge e importe numpy y pandas.

Cargue el dataset wage1 y guárdelo en una variable. Conserve únicamente las columnas exper, educ y wage.

Pase el dataframe a un array de numpy.

Sin ayuda de otra librería diferente a numpy:

Calcule los coeficientes


calcule los errores estándar


Calcule los estadísticos t

Calcule los intervalos de confianza

Interprete los coeficientes y determine la significancia estadística.






In [ ]:
!pip install wooldridge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 48.4 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np
import wooldridge as wd

In [ ]:
df=wd.data("wage1")

In [ ]:
df

wage  educ  exper  tenure  nonwhite  female  married  numdep  smsa  \
0     3.10    11      2       0         0       1        0       2     1   
1     3.24    12     22       2         0       1        1       3     1   
2     3.00    11      2       0         0       0        0       2     0   
3     6.00     8     44      28         0       0        1       0     1   
4     5.30    12      7       2         0       0        1       1     0   
..     ...   ...    ...     ...       ...     ...      ...     ...   ...   
521  15.00    16     14       2         0       1        1       2     0   
522   2.27    10      2       0         0       1        0       3     0   
523   4.67    15     13      18         0       0        1       3     0   
524  11.56    16      5       1         0       0        1       0     0   
525   3.50    14      5       4         1       1        0       2     0   

     northcen  ...  trcommpu  trade  services  profserv  profocc  clerocc  \
0           0  ...         0      0         0         0        0        0   
1           0  ...         0      0         1         0        0        0   
2           0  ...         0      1         0         0        0        0   
3           0  ...         0      0         0         0        0        1   
4           0  ...         0      0         0         0        0        0   
..        ...  ...       ...    ...       ...       ...      ...      ...   
521         0  ...         0      0         0         1        1        0   
522         0  ...         0      1         0         0        1        0   
523         0  ...         0      0         0         0        1        0   
524         0  ...         0      0         0         0        0        0   
525         0  ...         0      0         0         1        0        1   

     servocc     lwage  expersq  tenursq  
0          0  1.131402        4        0  
1          1  1.175573      484        4  
2          0  1.098612        4        0  
3          0  1.791759     1936      784  
4          0  1.667707       49        4  
..       ...       ...      ...      ...  
521        0  2.708050      196        4  
522        0  0.819780        4        0  
523        0  1.541159      169      324  
524        0  2.447551       25        1  
525        0  1.252763       25       16  

[526 rows x 24 columns]

In [ ]:
df= df[["wage","educ", "exper"]]

In [ ]:
X= df[["educ","exper"]]

y= df[["wage"]]

In [ ]:
y

wage
378  4.17
502  2.89
138  3.75
464  2.92
469  3.00
37   3.51
305  3.00
503  2.90
395  3.76
396  3.10
487  5.00
251  5.20
304  2.90
297  3.95
513  4.95
308  3.00
329  3.35
416  6.25
220  3.50
29   3.25

In [ ]:
X

educ  exper
378     0     22
502     0     42
138     2     39
464     3     51
469     4     36
37      4     39
305     4     48
503     5     34
395     6      6
396     6     14
487     6     18
251     6     47
304     6     49
297     6     49
513     7     25
308     7     26
329     7     35
416     7     39
220     8      4
29      8      9

In [ ]:
au=y.to_numpy()
au

array([[ 3.0999999 ],
       [ 3.24000001],
       [ 3.        ],
       [ 6.        ],
       [ 5.30000019],
       [ 8.75      ],
       [11.25      ],
       [ 5.        ],
       [ 3.5999999 ],
       [18.18000031],
       [ 6.25      ],
       [ 8.13000011],
       [ 8.77000046],
       [ 5.5       ],
       [22.20000076],
       [17.32999992],
       [ 7.5       ],
       [10.63000011],
       [ 3.5999999 ],
       [ 4.5       ],
       [ 6.88000011],
       [ 8.47999954],
       [ 6.32999992],
       [ 0.52999997],
       [ 6.        ],
       [ 9.56000042],
       [ 7.78000021],
       [12.5       ],
       [12.5       ],
       [ 3.25      ],
       [13.        ],
       [ 4.5       ],
       [ 9.68000031],
       [ 5.        ],
       [ 4.67999983],
       [ 4.26999998],
       [ 6.1500001 ],
       [ 3.50999999],
       [ 3.        ],
       [ 6.25      ],
       [ 7.80999994],
       [10.        ],
       [ 4.5       ],
       [ 4.        ],
       [ 6.38000011],
       [13

In [ ]:
df

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [ ]:
df

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [ ]:
x=np.c_[np.ones(len(X)),X]

In [ ]:
x

array([[ 1., 11.,  2.],
       [ 1., 12., 22.],
       [ 1., 11.,  2.],
       ...,
       [ 1., 15., 13.],
       [ 1., 16.,  5.],
       [ 1., 14.,  5.]])

In [ ]:
data=np.array(df)

In [ ]:
data

array([[ 3.0999999 , 11.        ,  2.        ],
       [ 3.24000001, 12.        , 22.        ],
       [ 3.        , 11.        ,  2.        ],
       ...,
       [ 4.67000008, 15.        , 13.        ],
       [11.56000042, 16.        ,  5.        ],
       [ 3.5       , 14.        ,  5.        ]])

In [ ]:
beta=np.linalg.inv(x.T.dot(x)).dot(x.T.dot(au))
beta

array([[-3.39053946],
       [ 0.64427208],
       [ 0.0700954 ]])

In [ ]:
y_est=x@beta

In [ ]:
y_est

array([[ 3.83664416],
       [ 5.88282415],
       [ 3.83664416],
       [ 4.84783456],
       [ 4.83139322],
       [ 7.54867231],
       [ 9.25778884],
       [ 4.69120242],
       [ 6.16320574],
       [ 9.10418453],
       [ 7.47857691],
       [ 5.19528371],
       [ 5.39215638],
       [ 5.60244257],
       [ 6.51368272],
       [ 7.89914929],
       [ 5.0416794 ],
       [ 6.10652385],
       [ 5.25196559],
       [ 6.8641597 ],
       [ 5.1117748 ],
       [ 6.37349193],
       [ 7.54867231],
       [ 4.55101163],
       [ 6.28998302],
       [ 7.12809993],
       [ 7.6888631 ],
       [ 9.09077102],
       [ 8.37640355],
       [ 2.39449571],
       [ 7.2414637 ],
       [ 5.76946039],
       [ 6.10652385],
       [ 4.83139322],
       [ 4.55101163],
       [ 8.45991246],
       [ 5.39215638],
       [ 1.92026928],
       [ 5.83955578],
       [ 5.1117748 ],
       [ 4.55101163],
       [ 5.74263336],
       [ 6.75079593],
       [ 6.85074619],
       [ 5.75604687],
       [ 7

In [ ]:
betas=y_est=beta[0]+beta[1]*x

In [ ]:
betas

array([[-2.74626739,  3.69645337, -2.10199531],
       [-2.74626739,  4.34072544, 10.7834462 ],
       [-2.74626739,  3.69645337, -2.10199531],
       ...,
       [-2.74626739,  6.27354167,  4.98499752],
       [-2.74626739,  6.91781375, -0.16917908],
       [-2.74626739,  5.62926959, -0.16917908]])

In [ ]:
def media(x):
  return sum(x)/len(x)

In [ ]:
media(x)

array([ 1.        , 12.56273764, 17.01711027])

In [ ]:
def varianza(x):
   n=media(x)
   l=[]
   for elem in x :
      l.append ((elem-n) ** 2)
   return sum(l)/(len(X)-1)

In [ ]:
varianza(x)

array([  0.        ,   7.66748506, 184.2035162 ])

In [ ]:
def desviacion(x):
  return (varianza(x)**0.5)

In [ ]:
desviacion(x)

array([ 0.       ,  2.7690224, 13.5721596])

In [ ]:
data=np.array(df)

In [ ]:
error=np.std(data) / np.sqrt(len(data))
error

0.41193634644892985

In [ ]:
t=beta/error
t

array([[-8.23073635],
       [ 1.56400881],
       [ 0.17016075]])

In [ ]:
confianza=[0.01,0.05,0.01]

In [ ]:
#intervalo de confianza modo 1
X = sm.add_constant(X) 
model = sm.OLS(y, X).fit()

print(model.conf_int())


              0         1
const -4.896466 -1.884613
exper  0.048530  0.091661
educ   0.538569  0.749975


In [ ]:
#intervalo de confianza modo 2 

t_value = 1.96
se_beta = np.sqrt(np.diag(var_cov_beta))
ci_lower = beta_hat - t_value * se_beta
ci_upper = beta_hat + t_value * se_beta

for i, var_name in enumerate(["wage", "exper", "educ"]):
    print(f"{var_name}: [{ci_lower[i]}, {ci_upper[i]}]")


wage: [-4.893009005726523, -1.8880699179717446]
exper: [0.048579230997745, 0.09161156091975531]
educ: [0.5388121757417235, 0.7497319751795324]


###interpretación
El coeficiente para la variable exp es 0,0786, lo que significa que por cada aumento de una unidad en la variable exper, se predice que la variable salario aumentará en 0,0786 unidades (manteniendo todas las demás variables constantes).

El coeficiente para la variable educ es 1,4472, lo que significa que por cada aumento de una unidad en la variable educ, se predice que la variable salario aumentará en 1,4472 unidades (manteniendo todas las demás variables constantes).

Para determinar la significación estadística de estos coeficientes, podemos observar las estadísticas t y sus valores p correspondientes. Un valor de p inferior a 0,05 indica significancia estadística. A partir del resultado, podemos ver que tanto las estadísticas t como los valores p son significativos para las variables exper y educ.

Por tanto, podemos concluir que tanto la variable exper como educ son  estadísticamente significativos de la variable salario en este modelo.